PARA INSTALACION DEL TEST

1 - COPIAR LAS CARPETAS RAIZ FRONTEND Y BACKEND EN SU SERVIDOR WEB DE REFERENCIA (APACHE, HTTPD, ETC).
2 - COPIGURAR EL SERVIDOR WEB CON LOS RESPECTIVOS HOST VIRTUALES PARA ACCEDER A LOS SERVICIOS WEB.

# ESTA CONFIGURACION DE EJEMPLO ES PARA APACHE - LARAVEL YA INCLUYE EL .htaccess CON LA CONFIGURACION IDEAL PARA EL REWRITE DEL index.php EN LA CARPETA PUBLICA
<VirtualHost frontend.com:80>
    ServerAdmin text@gmail.com
    DocumentRoot "C:/xampp/htdocs/frontend/public" # lugar donde se aloja el servicio web para el frontend
    ServerName frontend.com
    ServerAlias frontend
    ErrorLog "logs/frontend.log"
    CustomLog "logs/frontendcustom.log" common
</VirtualHost>

<VirtualHost backend.com:80>
    ServerAdmin text@gmail.com
    DocumentRoot "C:/xampp/htdocs/backend/public" # lugar donde se aloja el servicio web para el backend
    ServerName backend.com
    ServerAlias backend
    ErrorLog "logs/backend.log"
    CustomLog "logs/backendcustom.log" common
</VirtualHost>

3 - INSTALAR LOS PAQUETES PARA CADA SERVICIO WEB (FRONTEND - BACKEND)

# ACCERDER AL DIRECTORIO RAIZ DE CADA SERVICIO WEB ( cd C:\xampp\htdocs\backend ) DONDE C:\xampp\htdocs\backend ES LA UBICACION DONDE SE ENCUENTRA ALOJADO EL SERVICIO WEB

# EJECUTAR npm install DESPUES php artisan key:generate PARA CADA SERVICIO WEB (FRONTEND - BACKEND)

4 - CONFIGURAR EL ACCESO A LA BASE DE DATOS PRINCIPAL BD_SUN EN EL SERVICIO WEB BACKEND

# FICHERO DE CONFIGURACION .env 

DB_CONNECTION=mysql
DB_HOST=HOST
DB_PORT=3306
DB_DATABASE=db_sun
DB_USERNAME=USER
DB_PASSWORD=PASS

5 - CONFIGURAR LA URL DE ACCESO PARA CONSUMIR LOS SERVICIOS WEB DEL BACKEND PARA EL FRONTEND

# ESTA CONFIGURACION SE ENCUENTRA UBICADA EN EL FRONTEND EN frontend\resources\assets\js\config.js

var api_url = '';

switch( process.env.NODE_ENV ){
  case 'development':
    api_url = 'http://backend.com/api/'; /* sustituir backend.com por el IP o NOMBRE del servicio web */
  break;
  case 'production':
    api_url = 'http://backend.com/api/'; /* sustituir backend.com por el IP o NOMBRE del servicio web */
  break;
}

export const ROAST_CONFIG = {
  API_URL: api_url,
}

#PROXIMOS PASOS OPCIONALES ESCOJA EL QUE DESEE (PASOS 6 - 7)
6 - MIGRAR LAS TABLAS PARA LAS BASE DE DATOS DE LOS CLIENTES 

# INICIALMENTE CADA BASE DE DATOS DE CADA CLIENTE YA DEBE ESTAR CREADA EJEMPLO basededatosaconectar Y basededatosaconectar2 QUE SON LAS BASE DE DATOS QUE TIENEN LOS CLIENTES EN LA BASE DE DATOS db_sun

# EJECUTAR php artisan migrate EN EL SERVICIO WEB BACKEND - ESTO CREARA TODAS LAS TABLAS Y PROCEDIMIENTOS EN LAS BASES DE DATOS DE LOS CLIENTES ACTIVOS EN LA BD_SUN

7 - MIGRAR LAS TABLAS PARA LAS BASE DE DATOS DE LOS CLIENTES 

# INICIALMENTE CADA BASE DE DATOS DE CADA CLIENTE YA DEBE ESTAR CREADA EJEMPLO basededatosaconectar Y basededatosaconectar2 QUE SON LAS BASE DE DATOS QUE TIENEN LOS CLIENTES EN LA BASE DE DATOS db_sun

# EJECUTAR LOS SCRIPT PROPORCIONADOS basededatosaconectar.sql Y basededatosaconectar2.sql CON SU CLIENTE MYSQL PREFERIDO ESTO CREARA LAS 2 BASE DE DATOS DE CLIENTES ACTIVOS EN LA BASE DE DATOS PRINCIPAL BD_SUN

8 - ACCEDER DESDE SU NAVEGADOR WEB PREFERIDO EL SERVICIO WEB FRONTEND PARA COMENZAR A UTILIZAR EL TEST (http://frontend.com)

#NOTAS EXTRAS

# TODOS LOS METODOS Y FUNCIONES UTILIZADAS EN LOS SERVICIOS WEB ESTAN COMENTADAS CON SU UTILIDADES Y ACCIONES
#PARA EL MENSAJE DE LICENCIA PROXIMA A VENCER EN XX DIAS SE DEBE CAMBIAR ALGUNA FECHA DE FINALIZACION DE LAS LICENCIAS PARA QUE SEA MENOR A 10 DIAS A PARTIR DEL DIA EN QUE SE ESTA

